language: node_js
node_js:
- '7.7'

sudo:
  required

cache:
  yarn: true
  directories:
    - node_modules

before-script:
- yarn install

script:
- yarn test

after_success:
- yarn build


notifications:
  email: false
