language: node_js
  node_js:
    - 6

cache:
  yarn: true
  directories:
    - node_modules

before-script:
- yarn install

script:
- yarn test

after_success:
- yarn build

notifications:
  email: false
